### ISSUE TITLE
Kosmos showing as paying to both UK and Northern Ireland and Ireland, in fact only Ireland.

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resource-projects-dataload#22] opened 2015-11-06 12:28 UTC
Data shows only Ireland.
Probably lookup of country ID gets double hit?
http://alpha.resourceprojects.org/project/IE/fe31-jcvrob.html

**Comment by timgdavies** [comment] 2015-11-16 12:34
Duplicate of #23. Closing

**Closed as completed by timgdavies** 2015-11-16 12:34 UTC
